# Generated by Django 5.0.7 on 2026-03-02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=250)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("payout_account_name", models.CharField(max_length=150)),
                ("payout_account_number", models.CharField(max_length=50)),
                ("payout_ifsc", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SellerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("own_delivery", "Own delivery"),
                            ("hub_delivery", "Hub handover"),
                        ],
                        default="own_delivery",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_details",
                    models.TextField(
                        blank=True,
                        help_text="Required when delivery mode is own delivery.",
                    ),
                ),
                ("hub_name", models.CharField(blank=True, max_length=120)),
                ("hub_address", models.TextField(blank=True)),
                ("handover_instructions", models.TextField(blank=True)),
                (
                    "payout_rate_own_delivery",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90.00"),
                        help_text="Percentage paid to seller for own delivery.",
                        max_digits=5,
                    ),
                ),
                (
                    "payout_rate_hub_delivery",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("82.00"),
                        help_text="Percentage paid to seller for hub handover.",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_product",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_products",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("own_delivery", "Own delivery"),
                            ("hub_delivery", "Hub handover"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payout_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("payout_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_payout",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]

