# Generated by Django 5.2.11 on 2026-03-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0002_sellernotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerpayout",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("packed", "Packed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("handed_to_hub", "Handed over to hub"),
                    ("at_hub", "Received at hub"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sellerpayout",
            name="delivery_status_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sellerpayout",
            name="delivery_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerpayout",
            name="delivery_status_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_seller_delivery_status",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

