# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sellers", "0003_sellerpayout_delivery_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerpayout",
            name="courier_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sellerpayout",
            name="courier_slip",
            field=models.ImageField(blank=True, null=True, upload_to="courier_slips/"),
        ),
    ]
