# Generated by Django 5.2.11 on 2026-03-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_sellerpayout_courier_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedSellerPayout',
            fields=[
            ],
            options={
                'verbose_name': 'Completed order',
                'verbose_name_plural': 'Completed orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sellers.sellerpayout',),
        ),
        migrations.AlterField(
            model_name='sellernotification',
            name='notification_type',
            field=models.CharField(choices=[('seller_order', 'Seller order alert'), ('admin_order', 'Admin order alert'), ('delivery_update', 'Delivery status update')], max_length=30),
        ),
    ]
