# Generated by Django 5.2.11 on 2026-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_pan_card_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_pan_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_documents/business_pan_cards/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='payout_upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
