# Generated by Django 5.2.11 on 2026-03-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0010_sellerprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
