# Generated by Django 5.2.11 on 2026-03-24 10:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_return_shipping_charge_and_more'),
        ('sellers', '0011_sellerprofile_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default payout config', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('payment_gateway_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('additional_hold_days', models.PositiveIntegerField(default=7)),
                ('default_return_window_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payout configuration',
                'verbose_name_plural': 'Payout configurations',
            },
        ),
        migrations.AlterField(
            model_name='sellernotification',
            name='notification_type',
            field=models.CharField(choices=[('seller_order', 'Seller order alert'), ('admin_order', 'Admin order alert'), ('delivery_update', 'Delivery status update'), ('balance_available', 'Balance available'), ('payout_completed', 'Payout completed'), ('deduction_applied', 'Deduction applied')], max_length=30),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_wallet_payouts', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('component', models.CharField(choices=[('product_price', 'Product price'), ('commission', 'Commission'), ('gateway_fee', 'Gateway fee'), ('shipping', 'Shipping'), ('return_shipping', 'Return shipping'), ('seller_discount', 'Seller discount'), ('gst', 'GST'), ('tds', 'TDS'), ('payout', 'Payout'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('available', 'Available'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('reference_id', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=150, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_ledger_entries', to='orders.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sellers.payout')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellerOrderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('hold', 'Hold'), ('available', 'Available'), ('paid', 'Paid'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('hold_days', models.PositiveIntegerField(default=7)),
                ('return_window_closed_at', models.DateTimeField(blank=True, null=True)),
                ('available_on', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_order_payouts', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payouts', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hold_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='sellers.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller wallet',
                'verbose_name_plural': 'Seller wallets',
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ledger_created', 'Ledger created'), ('ledger_status_updated', 'Ledger status updated'), ('return_processed', 'Return processed'), ('payout_initiated', 'Payout initiated'), ('payout_completed', 'Payout completed'), ('payout_failed', 'Payout failed'), ('wallet_recalculated', 'Wallet recalculated'), ('manual_adjustment', 'Manual adjustment')], max_length=40)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=150)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='sellers.sellerledger')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_transaction_logs', to='orders.order')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='sellers.payout')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='sellerledger',
            index=models.Index(fields=['seller', 'status', 'created_at'], name='sellers_sel_seller__ae5ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerledger',
            index=models.Index(fields=['order', 'status'], name='sellers_sel_order_i_c1f31f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerledger',
            index=models.Index(fields=['reference_id'], name='sellers_sel_referen_add771_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerorderpayout',
            constraint=models.UniqueConstraint(fields=('seller', 'order'), name='uniq_seller_order_payout'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['seller', 'action', 'created_at'], name='sellers_tra_seller__5d0443_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['idempotency_key'], name='sellers_tra_idempot_ecf5d8_idx'),
        ),
    ]
