# Generated by Django 5.2.11 on 2026-03-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0012_payoutconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayout',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sellerpayout',
            name='delivery_type',
            field=models.CharField(choices=[('platform', 'Platform delivery'), ('own_delivery', 'Own delivery')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerpayout',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerpayout',
            name='razorpay_payout_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='delivery_type',
            field=models.CharField(choices=[('platform', 'Platform delivery'), ('own_delivery', 'Own delivery')], default='own_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='estimated_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
