# Generated by Django 5.2.11 on 2026-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0013_sellerpayout_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_signature',
            field=models.ImageField(blank=True, null=True, upload_to='seller_documents/signatures/'),
        ),
    ]
