# Generated by Django 5.2.11 on 2026-04-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_orderidentifiersequence_order_public_id_and_more'),
        ('sellers', '0015_sellerprofile_payout_phonepay_gpay_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', 'status'], name='sellers_pay_seller__676e49_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', 'created_at'], name='sellers_pay_seller__22218c_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'created_at'], name='sellers_pay_status_2d2a30_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['idempotency_key'], name='sellers_pay_idempot_3b9224_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerorderpayout',
            index=models.Index(fields=['seller', 'status'], name='sellers_sel_seller__acffd8_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerorderpayout',
            index=models.Index(fields=['seller', 'updated_at'], name='sellers_sel_seller__0dc390_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerorderpayout',
            index=models.Index(fields=['status', 'available_on'], name='sellers_sel_status_6658b2_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerorderpayout',
            index=models.Index(fields=['seller', 'status', 'created_at'], name='sellers_sel_seller__118526_idx'),
        ),
    ]
