# Generated by Django 6.0.4 on 2026-04-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0017_sellerprofile_brand_name_and_registration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_id',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
