# Generated by Django 5.2.11 on 2026-04-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0018_alter_sellerprofile_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
