# Generated by Django 5.2.11 on 2026-05-14 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_products_pr_status_26fa5b_idx_and_more'),
        ('sellers', '0021_alter_sellerprofile_seller_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['seller', 'delivery_mode'], name='sellers_sel_seller__f58451_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['seller', 'delivery_type'], name='sellers_sel_seller__8a9e96_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerproduct',
            index=models.Index(fields=['updated_at'], name='sellers_sel_updated_303bed_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['approval_status', 'approved_at'], name='sellers_sel_approva_4557d1_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['user', 'approval_status'], name='sellers_sel_user_id_22d653_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['business_name'], name='sellers_sel_busines_73ffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['contact_email'], name='sellers_sel_contact_c5dc39_idx'),
        ),
    ]
