# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_coupon_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cod", "Cash on delivery"), ("online", "Online payment")],
                default="cod",
                max_length=20,
            ),
        ),
    ]

