# Generated by Django 5.2.11 on 2026-03-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_payment_method"),
        ("products", "0001_initial"),
        ("sellers", "0004_sellerpayout_courier_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupons",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupons",
                to="sellers.sellerprofile",
            ),
        ),
    ]
