# Generated by Django 5.2 on 2026-03-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_paymenttransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("picked_up", "Picked up"),
                            ("out_for_delivery", "Out for delivery"),
                            ("delivered", "Delivered"),
                            ("delivery_failed", "Delivery failed"),
                            ("returned", "Returned"),
                        ],
                        default="assigned",
                        max_length=30,
                    ),
                ),
                (
                    "cod_payment_status",
                    models.CharField(
                        choices=[
                            ("not_applicable", "Not applicable"),
                            ("pending_collection", "Pending collection"),
                            ("collected", "Collected"),
                            ("collection_failed", "Collection failed"),
                        ],
                        default="not_applicable",
                        max_length=30,
                    ),
                ),
                ("cod_collected_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("customer_note", models.CharField(blank=True, max_length=255)),
                ("internal_note", models.CharField(blank=True, max_length=255)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cod_collected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_assignment",
                        to="orders.order",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_delivery_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-created_at"),
            },
        ),
    ]
