# Generated by Django 5.2.11 on 2026-03-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_returnrequest_wallet'),
        ('products', '0004_product_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='returnrequest',
            unique_together={('order', 'product')},
        ),
    ]
