# Generated by Django 5.2.11 on 2026-03-23 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_verified_purchase(apps, schema_editor):
    Review = apps.get_model("orders", "Review")
    Review.objects.filter(order_item__isnull=False).update(is_verified_purchase=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_legacy_is_cancelled_compat'),
        ('products', '0005_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_review_per_user_product'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='orders.review'),
        ),
        migrations.RunPython(populate_verified_purchase, noop_reverse),
        migrations.RemoveField(
            model_name='review',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(fields=('review', 'reported_by'), name='unique_review_report_per_user'),
        ),
    ]
