# Generated by Django 5.2.11 on 2026-03-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_reviewreport_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_user_product',
        ),
    ]
