# Generated by Django 5.2.11 on 2026-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_review_unique_review_per_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='return_window_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
