# Generated by Django 5.2.11 on 2026-04-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_delivery_charge_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('partially_cancelled', 'Partially cancelled'), ('cancelled', 'Cancelled')], default='placed', max_length=30),
        ),
    ]
