# Generated by Django 5.2.11 on 2026-04-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_status'),
        ('orders', '0021_coupon_minimum_purchase_amount'),
    ]

    operations = [
    ]
