# Generated by Django 5.2.11 on 2026-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_gateway_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('paid', 'Paid'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('partially_cancelled', 'Partially cancelled'), ('cancelled', 'Cancelled')], default='placed', max_length=30),
        ),
    ]
