# Generated by Django 5.2.11 on 2026-04-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('picked_up', 'Picked Up'), ('refunded', 'Refunded'), ('rejected', 'Rejected'), ('shipped_by_buyer', 'Shipped by Buyer'), ('received_by_seller', 'Received by Seller'), ('refund_completed', 'Refund Completed')], default='pending', max_length=20),
        ),
    ]
