# Generated by Django 5.2.11 on 2026-05-14 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_city_order_country_order_pincode_order_state'),
        ('products', '0013_product_products_pr_status_26fa5b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Cancelled Order', 'verbose_name_plural': 'Cancelled Orders'},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', 'created_at'], name='orders_orde_order_s_cb4553_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'created_at'], name='orders_orde_payment_2d60e5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_type', 'created_at'], name='orders_orde_deliver_fbdc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paid', 'created_at'], name='orders_orde_paid_046b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='orders_paym_status_7009c3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['gateway', 'created_at'], name='orders_paym_gateway_98995b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_method', 'created_at'], name='orders_paym_payment_b7e00d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'created_at'], name='orders_paym_user_id_0e80d3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order', 'created_at'], name='orders_paym_order_i_95152d_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', 'created_at'], name='orders_retu_status_780092_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['reason', 'created_at'], name='orders_retu_reason_ed933a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', 'created_at'], name='orders_retu_user_id_41b529_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['product', 'created_at'], name='orders_retu_product_8a9690_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'created_at'], name='orders_retu_order_i_0cc032_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating', 'created_at'], name='orders_revi_rating_11656e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase', 'created_at'], name='orders_revi_is_veri_94e1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_reported', 'created_at'], name='orders_revi_is_repo_75e97d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_flagged', 'created_at'], name='orders_revi_is_flag_d18239_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'created_at'], name='orders_revi_user_id_1d8a09_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'created_at'], name='orders_revi_product_7bb53c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', 'created_at'], name='orders_revi_status_a28ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['reported_by', 'created_at'], name='orders_revi_reporte_b404c2_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['review', 'created_at'], name='orders_revi_review__344b74_idx'),
        ),
    ]
