# Generated by Django 5.2.11 on 2026-04-16 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_brand_productimage_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'size', 'color'], name='products_pr_product_fb9cfd_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_variant_combination')],
            },
        ),
    ]
