# Generated by Django 6.0.4 on 2026-04-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_approved_at_product_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
