# Generated by Codex on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_product_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
