# Generated by Django 5.2.11 on 2026-04-28 06:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_status_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('18.00'), help_text='GST rate as percentage for this category.', max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
