# Generated by Django 5.2.11 on 2026-04-30 06:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_gst_rate_category_hsn_code_product_gst_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'No GST / 0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('18.00'), help_text='GST rate as percentage for this category.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'No GST / 0%'), (Decimal('5.00'), '5%'), (Decimal('12.00'), '12%'), (Decimal('18.00'), '18%'), (Decimal('28.00'), '28%')], decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
    ]
