# Generated by Django 5.2.11 on 2026-05-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_category_gst_rate_alter_product_gst_rate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'created'], name='products_pr_status_26fa5b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'created'], name='products_pr_availab_3f0970_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'created'], name='products_pr_categor_224cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated'], name='products_pr_updated_c4b653_idx'),
        ),
    ]
